services:
  app:
    image: 'backend'
    build: .
    ports:
      - 8000:8000
    container_name: backendprueba
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tingeso
      - SPRING_DATASOURCE_USERNAME=tingeso
      - SPRING_DATASOURCE_PASSWORD=1234
          
  db:
    image: 'postgrest'
    container_name: postgrestPrueba
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=tingeso
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=tingeso
    volumes:
      - ./createDB.sql:/docker-entrypoint-initdb.d/createDB.sql