node{

      stage("Repo"){
        checkout scm
        sh 'echo "ayudaaaa"'
      }

      stage('JunitTest') {
          catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                    dir("/var/lib/jenkins/workspace/Tingeso/demo") {
                        sh 'chmod +x ./gradlew'
                        sh './gradlew test'
                    }
          }
  		}

     stage('SonarQube analysis') {
    			
				dir("/var/lib/jenkins/workspace/Tingeso/demo") {
					withSonarQubeEnv('sonarqube') { // Will pick the global server connection you have configured
                        sh 'chmod 777 ./gradlew'
                        sh './gradlew sonarqube'
    					}
				
			  }
  		}

      

      stage("build") {
          sh """ docker build --build-arg JAR_FILE=build/libs/\\*.jar -t demo ."""
      }
      stage("run") {
        sh 'docker run -i -p 8081:8081 demo'
      }
}