version: '2'

services:
  app:
    image: 'backend'
    build: .
    ports:
      - 8081:8081
    container_name: backendprueba
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tingeso
      - SPRING_DATASOURCE_USERNAME=tingeso
      - SPRING_DATASOURCE_PASSWORD=1234   
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - franciscavera/frontend-ev2:latest
  app-client:
    image: franciscavera/frontend-ev2:latest
    container_name: frontend
 # Map the exposed port 80 on the container to port 9090 on the host machine
    restart: always
    depends_on:
      - db
      - backend
    networks:
      - franciscavera/frontend-ev2:latest
      - backend
  db:
    image: postgres:14.1
    container_name: pruebaDB
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=tingeso
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=tingeso
    volumes:
      - ./BaseDatos/createDB.sql:/docker-entrypoint-initdb.d/createDB.sql
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
      - franciscavera/frontend-ev2:latest

volumes:
    createDB.sql:
networks:
  backend:
  franciscavera/frontend-ev2:latest: 